NewsPort/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('news.urls', namespace='default')),
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),
]

news/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import PostsList, PostDetailView, PostSearch, PostCreateView, \
    PostUpdateView, PostDeleteView, CategoriesListView, CategoryDetailView, subscribe_to, unsubscribe_from

app_name = 'news'
urlpatterns = [
    # path('', cache_page(10*1)(PostsList.as_view()), name='posts'),  # D7.3. Кэширование в Django (view, url)
    path('', PostsList.as_view(), name='posts'),
    path('search/', PostSearch.as_view()),

    # path('<int:pk>', cache_page(10*5)(PostDetailView.as_view()), name='post_detail'),
    path('<int:pk>', PostDetailView.as_view(), name='post_detail'),
    path('add/', PostCreateView.as_view(), name='post_create'),

    path('<int:pk>/edit/', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),

    path('categories/', CategoriesListView.as_view(), name='categories'),
    path('categories/<int:pk>', CategoryDetailView.as_view(), name='category_detail'),

    path('subscribe/<int:pk>', subscribe_to, name='subscribe'),
    path('unsubscribe/<int:pk>', unsubscribe_from, name='unsubscribe'),

]

news/models.py
from django.contrib.auth.models import User
from django.core.cache import cache
from django.db import models
from django.db.models import Sum


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def __str__(self):
        return self.authorUser.username

    def update_rating(self):
        postRat = self.post_set.all().aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.all().aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        # ------суммарный рейтинг всех комментариев к статьям автора.---------
        posts = self.post_set.all()
        commentPostRat = 0
        for post in posts:
            commentPostRow = post.comment_set.all().aggregate(cpRating=Sum('rating'))
            commentPostRat += commentPostRow.get('cpRating')
        self.ratingAuthor = pRat * 3 + cRat + commentPostRat
        # -------------------------------
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/news/categories/{self.pk}'


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name='Автор')

    NEWS = 'NW'
    ARTICLE = 'AR'

    TYPES = [
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
    ]

    categoryType = models.CharField(max_length=2, choices=TYPES, default=ARTICLE, verbose_name='Тип статьи')
    dateCreation = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    postCategory = models.ManyToManyField(Category, through='PostCategory', verbose_name='Категории статьи')
    title = models.CharField(max_length=128, verbose_name='Заголовок')
    text = models.TextField(verbose_name='Текст статьи')
    rating = models.SmallIntegerField(default=0, verbose_name='Рейтинг')

    @property
    def in_categories(self):
        list_categories = []
        for c in self.postCategory.all():
            list_categories.append(c.name)
        return list_categories

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # добавим абсолютный путь, чтобы после создания нас перебрасывало на страницу с товаром
        return f'/news/{self.pk}'

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:123] + '...'

    # D7.4.Кэширование на низком уровне (смотри еще view PostDetailView метод get_object)
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'product-{self.pk}')  # затем удаляем его из кэша, чтобы сбросить его


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.categoryThrough}: {self.postThrough}'


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def __str__(self):
        return f'{self.commentUser.username}: {self.commentPost.title}: {self.text[0:15] + "..."}'

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

news/forms.py
from django.forms import ModelForm
from .models import Post, Category
from django import forms


# Создаём модельную форму
class PostForm(ModelForm):
    # В класс мета, как обычно, надо написать модель,
    # по которой будет строиться форма, и нужные нам поля.
    # Мы уже делали что-то похожее с фильтрами
    class Meta:
        model = Post
        fields = ['author', 'categoryType', 'postCategory',
                  'title', 'text']

        widgets = {
            'author': forms.Select(attrs={'class': 'form-control'}),
            'categoryType': forms.Select(attrs={'class': 'form-control',}),
            'postCategory': forms.SelectMultiple(attrs={'class': 'form-control',}),
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите название статьи или новости'
            }),
            'text': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Сама статья'
            }),
        }

news/views.py
import logging
from time import timezone

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.cache import cache
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import redirect
from django.template.loader import render_to_string

from django.urls import reverse_lazy, resolve
from django.utils import timezone
from django.views.generic import ListView, UpdateView, CreateView, DetailView, DeleteView

from .models import Post, Category
from .filters import PostFilter
from .forms import PostForm
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
# from django.views.decorators.cache import cache_page

DEFAULT_FROM_EMAIL = settings.DEFAULT_FROM_EMAIL
logger = logging.getLogger("django")


# @cache_page(60 * 15)  # D7.3. Кэширование в Django (view)
class PostsList(ListView):
    model = Post
    template_name = 'news/posts.html'
    context_object_name = 'posts'
    ordering = ['-dateCreation']
    form_class = PostForm
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = timezone.localtime(timezone.now())  # добавим переменную текущей даты time_now
        context['posts_count'] = Post.objects.all().count()  # добавим переменную кол-во постов
        context['form'] = PostForm()
        context['is_not_authors'] = not self.request.user.groups.filter(name='authors').exists()
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)  # создаём новую форму, забиваем в неё данные из POST-запроса
        if form.is_valid():  # если пользователь ввёл всё правильно и нигде не накосячил, то сохраняем новый товар
            form.save()
        return super().get(request, *args, **kwargs)


class PostSearch(ListView):
    model = Post
    template_name = 'news/postSearch.html'
    context_object_name = 'posts'
    ordering = ['-id']
    form_class = PostForm
    paginate_by = 5

    def get_queryset(self):
        queryset = PostFilter(self.request.GET, super().get_queryset()).qs
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = timezone.localtime(timezone.now())  # добавим переменную текущей даты time_now
        context['posts_count'] = Post.objects.all().count()  # добавим переменную кол-во постов всего
        context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())
        context['is_not_authors'] = not self.request.user.groups.filter(name='authors').exists()
        return context


class PostDetailView(DetailView):
    template_name = 'news/post_detail.html'
    queryset = Post.objects.all()

    # D7.4 Кэширование на низком уровне (смотри еще модель Post метод save)
    def get_object(self, *args, **kwargs):  # переопределяем метод получения объекта, как ни странно
        obj = cache.get(f'product-{self.kwargs["pk"]}', None)  # кэш очень похож на словарь, и
        # метод get действует также. Он забирает значение по ключу, если его нет, то забирает None.

        # если объекта нет в кэше, то получаем его и записываем в кэш
        if not obj:
            obj = super().get_object(queryset=self.queryset)
            cache.set(f'product-{self.kwargs["pk"]}', obj)
        return obj


# class PostCreateView(LoginRequiredMixin, CreateView):
class PostCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'news/post_create.html'
    form_class = PostForm
    permission_required = ('news.add_post',)


class PostUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'news/post_update.html'
    form_class = PostForm
    permission_required = ('news.change_post',)

    def get_object(self, **kwargs):
        id_pk = self.kwargs.get('pk')
        return Post.objects.get(pk=id_pk)


class PostDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'news/post_delete.html'
    queryset = Post.objects.all()
    success_url = reverse_lazy('news:posts')
    permission_required = ('news.delete_post',)


class CategoriesListView(ListView):
    model = Category
    template_name = 'news/categories.html'
    context_object_name = 'categories'
    ordering = ['-name']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_authors'] = not self.request.user.groups.filter(name='authors').exists()
        return context


class CategoryDetailView(ListView):
    model = Category
    template_name = 'news/posts.html'
    context_object_name = 'posts'
    ordering = ['-id']
    # ordering = ['-dateCreation']
    paginate_by = 5

    def get_queryset(self):
        cat = Category.objects.get(pk=self.kwargs['pk'])
        queryset = cat.post_set.order_by('-pk')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.get(pk=self.kwargs['pk'])
        context['time_now'] = timezone.localtime(timezone.now())  # добавим переменную текущей даты time_now
        context['is_not_authors'] = not self.request.user.groups.filter(name='authors').exists()
        return context


@login_required()
def subscribe_to(request, pk):
    user = request.user
    category = Category.objects.get(pk=pk)
    logger.info(f"== Пользователь: '{user}' подписался на категорию: '{category}' ==")

    if not category.subscribers.filter(pk=user.id).exists():
        category.subscribers.add(user)
        email = user.email
        html = render_to_string(
            'mail/subscribe.html',
            {
                'category': category,
                'user': user
            },
        )
        msg = EmailMultiAlternatives(
            subject=f'Вы подписались на категорию {category}',
            body='',
            from_email=DEFAULT_FROM_EMAIL,
            to=[email, ],
        )

        msg.attach_alternative(html, 'text/html')

        try:
            msg.send()
        except Exception as e:
            print(e)
        # return redirect(request.META.get('HTTP_REFERER'))
        return redirect('news:categories')

    return redirect(request.META.get('HTTP_REFERER'))
    # return redirect('news:categories')


@login_required()
def unsubscribe_from(request, pk):
    user = request.user
    category = Category.objects.get(pk=pk)
    logger.info(f"== Пользователь: '{user}' отписался от категории: '{category}' ==")
    if category.subscribers.filter(id=user.id).exists():
        category.subscribers.remove(user)
    return redirect('news:categories')
    # return redirect(request.META.get('HTTP_REFERER'))


# --------------------------------
# def div_zero():
#     result = 5 / 0
#     logger.error("Деление на ноль!!!")

# -------------------------------
# class Category2DetailView(ListView):
#     model = Post
#     template_name = 'news/posts.html'
#     context_object_name = 'posts'
#     ordering = ['-id']
#     paginate_by = 3
#
#     def get_queryset(self):
#         self.id = resolve(self.request.path_info).kwargs['pk']
#         print("==1 =====", self.id)
#         print("== 1.1 =====", self.kwargs['pk'])
#
#         cat = Category.objects.get(pk=self.kwargs['pk'])
#         queryset = cat.post_set.order_by('-pk')
#         return queryset
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         print("==2 =====", self.id)
#         print("== 2.2 =====", self.kwargs['pk'])
#         context['category'] = Category.objects.get(pk=self.kwargs['pk'])
#         context['time_now'] = timezone.localtime(timezone.now())  # добавим переменную текущей даты time_now
#         context['is_not_authors'] = not self.request.user.groups.filter(name='authors').exists()
#         return context
# -------------------------------

news/templates/news/categories.html
{% extends 'layout/default.html' %}

{% load custom_filters %}

{% block title %}
    Категории новостей
{% endblock title %}

{% block content %}
    <h1 align="center">Категории новостей и статей:</h1>

    <div class="d-flex justify-content-center flex-wrap">

        {% for category in categories %}

            <div class="w-30 p-2 col-sm-4" style="width: 300px">
                <div class="card">
                    <div class="card-body">
                        <a href="{% url 'news:category_detail' category.pk %}" class="btn btn-primary btn-lg">{{ category.name }}</a>
                        {% if user in category.subscribers.filter %}
                            <button type="button" class="btn btn-info btn-sm" disabled>Вы подписаны</button>
                        {% endif %}

                        <br><br>
                        <p class="card-text"> Статей: {{ category.post_set.count }}</p>
                        <p class="card-text"> Подписчиков: {{ category.subscribers.count }}</p>
                        <a href="{% url 'news:category_detail' category.pk %}" class="btn btn-info">Статьи</a>

                        {% if user not in category.subscribers.filter %}
                            <a href="{% url 'news:subscribe' category.pk %}" class="btn btn-primary btn-sm">Подписаться</a>
                        {% else %}
                            <a href="{% url 'news:unsubscribe' category.pk %}" class="btn btn-secondary btn-sm">Отписаться</a>
                        {% endif %}
                    </div>
                </div>
            </div>

        {% endfor %}

    </div>

{% endblock content %}

news/templates/news/post.html
{% extends 'layout/default.html' %}

<!-- не забываем заранее загружать наши фильтры! -->
{% load custom_filters %}

<!-- Название у нас будет "Новость или статья - Заголовок..." -->
{% block title %}
    {{ post.get_categoryType_display }}: {{ post.title|truncatechars:10  }}
{% endblock title %}

<!-- В контенте на странице мы выводим саму Новость или статью,
 первичный ключ которого был передан в адрес -->
{% block content %}
    <h1 align="center">{{ post.title|Censor }}</h1>
    <hr>
    <p>{{ post.text|Censor }}</p>
    <h5 align="right">{{ post.dateCreation| date:'d-M-Y H:i' }}</h5>
{% endblock content %}

news/templates/news/postSearch.html
<!--  наследуемся от шаблона base.html -->
{% extends 'layout/default.html' %}

<!-- не забываем заранее загружать наши фильтры! -->
{% load custom_filters %}

<!-- Название у нас будет Новости, статьи -->
{% block title %}
    Поиск новости, статьи
{% endblock title %}

<!-- В контенте на странице мы выводим все посты -->
{% block content %}
    <h1 align="center" >Поиск новости или статьи:</h1>
    <h5 align="right">{{ time_now| date:'d-M-Y H:i' }}</h5>
    <hr>
    <h5 align="center"><i><u> Найдено новостей и статей: {{ filter.qs|length }} из {{ posts_count }}</u></i></h5>
    <br>

    {% if posts %}

        <!-- Перед таблицей добавим форму для поиска -->
        <form method="GET">
            {{ filter.form }}
            <!-- Форму от фильтров за нас сделает Django. А вот кнопку, увы, придётся делать самим -->
            <input class="btn btn-primary" type="submit" value="Найти">
        </form>

        <table class="table">
            <tr>
                <th scope="col"> Название</th>
                <th scope="col"><p align="justify"> Дата публикации</p></th>
                <th scope="col">Содержимое</th>
                <th scope="col">Действия</th>

            </tr>
            {#            {% for post in filter.qs %}#}
            {% for post in posts %}
                <tr class="{% cycle 'blue_tr' 'white_tr' %}">
                    <td>
                        <a href="{% url 'news:post_detail' post.pk %}">
                            {{ post.title|truncatewords:8|truncatechars:50|Censor }}
                        </a>
                    </td>
                    <td>{{ post.dateCreation| date:'d-M-Y H:i' }}</td>
                    <td>{{ post.text|truncatechars:50|Censor }}</td>
                    <td>
                        <a href="{% url 'news:post_update' post.pk %}">Редактирование</a>
                        <a href="{% url 'news:post_delete' post.pk %}">Удалить</a>
                    </td>
                </tr>
            {% endfor %}

        </table>

        {% include 'news/parts/paginator.html' %}

    {% else %}
        <h2 align="center">Новостей и статей нет!</h2>

    {% endif %}

{% endblock content %}

news/templates/news/post_create.html
{% extends 'layout/default.html' %}


{% block title %}
Создание статьи
{% endblock title %}

{% block content %}

<h3>Добавление статьи или новости</h3>

<form method="POST">
 {% csrf_token %}
 {{ form }}
   <!-- Теперь нам нужна только готовая форма и кнопка -->
   <input class="btn btn-success my-button" type="submit" value="Добавить">
</form>

{% endblock content %}

news/templates/news/post_delete.html
{% extends 'layout/default.html' %}

{% block title %}
    Удаление статьи
{% endblock title %}

{% block content %}
    <h3>Вы действительно хотите удалить статью?</h3>
    <div class="card">
        <div class="card-header">
            <h3>{{ post.title }} </h3>
            <div>
                Автор: <span class="badge bg-info">{{ post.author }}</span>
                Тип: <span class="badge bg-info">{{ post.get_categoryType_display }}</span>

                Категории:
                <span class="badge bg-info">
                    {% for k in  post.postCategory.all %}
                        {{ k }},
                    {% endfor %}
                </span>

            </div>
        </div>
        <div class="card-body">{{ post.text }}</div>
    </div>
    <form method="POST">
        {% csrf_token %}
        <input class="btn btn-success my-button" type="submit" value="Подтвердить">
    </form>

{% endblock content %}

news/templates/news/post_detail.html
{% extends 'layout/default.html' %}

{% load custom_filters %}

{% block title %}
    Новость: {{ post.title }}
{% endblock title %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <h3>{{ post.title|Censor2 }}</h3>
            <div>
                Автор: <span class="badge bg-info">{{ post.author }}</span>
                Тип: <span class="badge bg-info">{{ post.get_categoryType_display }}</span>
                {#        Категории: <span class="badge bg-info">{{ post.postCategory.name }}</span>#}
                {#        Категории: <span class="badge bg-info">{{ post.postCategory.all }}</span>#}
                Категории:
                <span class="badge bg-info">
                    {% for k in  post.postCategory.all %}
                        {{ k }},
                    {% endfor %}
                </span>
            </div>
        </div>
        <div class="card-body">{{ post.text|Censor2 }}</div>
    </div>
    <a href="{% url 'news:posts' %}" class="btn btn-primary my-3">В начало</a>

{% endblock content %}

news/templates/news/post_update.html
{% extends 'layout/default.html' %}


{% block title %}
Редактирование статьи
{% endblock title %}

{% block content %}
<h3>Редактирование статьи или новости</h3>

<form method="POST">
 {% csrf_token %}
 {{ form }}
   <input class="btn btn-success my-button" type="submit" value="Изменить">
</form>

{% endblock content %}

news/templates/news/posts.html
{% extends 'layout/default.html' %}

<!-- не забываем заранее загружать наши фильтры! -->
{% load custom_filters %}

<!-- Название у нас будет Новости, статьи -->
{% block title %}
    Новости, статьи
{% endblock title %}

<!-- В контенте на странице мы выводим все посты -->
{% block content %}
    {% if category %}
        {% if user not in category.subscribers.filter %}
            <a href="{% url 'news:subscribe' category.pk %}" class="btn btn-primary">Подписаться</a>
        {% else %}
            <a href="{% url 'news:unsubscribe' category.pk %}" class="btn btn-secondary btn-sm">Отписаться</a>
        {% endif %}

        <h1 align="center" >Новости и статьи категории `{{ category.name }}`:</h1>

        <h5 align="center"><i><u> Всего новостей и статей: {{ category.post_set.count }}
            (на странице: {{ posts|length }})</u></i>
        </h5>
    {% else %}
        <h1 align="center" >Все новости и статьи:</h1>
        <h5 align="center"><i><u> Всего новостей и статей: {{ posts_count }}
            (на странице: {{ posts|length }})</u></i>
        </h5>
    {% endif %}

    <h5 align="right">{{ time_now| date:'d-M-Y H:i' }}</h5>
    <hr>

    {% if posts %}
        <table class="table">
            <tr>
                <th scope="col"> Название</th>
                <th scope="col"><p align="justify"> Дата публикации</p></th>
                <th scope="col">Содержимое</th>
                <th scope="col">Действия</th>
            </tr>
            {% for post in posts %}
                <tr class="{% cycle 'blue_tr' 'white_tr' %}">
                    <td>
                        <a href="{% url 'news:post_detail' post.pk %}">
                            {{ post.title|truncatewords:8|truncatechars:50|Censor2 }}
                        </a>
                    </td>
                    <td>{{ post.dateCreation| date:'d-M-Y H:i' }}</td>
                    <td>{{ post.text|truncatechars:50|Censor2 }}</td>
                    <td>
                        <a href="{% url 'news:post_update' post.pk %}">Редактирование</a>
                        <a href="{% url 'news:post_delete' post.pk %}">Удалить</a>
                    </td>
                </tr>
            {% endfor %}
        </table>

        {% include 'news/parts/paginator.html' %}

    {% else %}
        <h2>Новостей и статей нет!</h2>

    {% endif %}

{% endblock content %}