NewsPort/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('news.urls', namespace='default')),
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
    path('sign/', include('sign.urls')),
    path('accounts/', include('allauth.urls')),
]

news/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import PostsList, PostDetailView, PostSearch, PostCreateView, \
    PostUpdateView, PostDeleteView, CategoriesListView, CategoryDetailView, subscribe_to, unsubscribe_from

app_name = 'news'
urlpatterns = [
    # path('', cache_page(10*1)(PostsList.as_view()), name='posts'),  # D7.3. Кэширование в Django (view, url)
    path('', PostsList.as_view(), name='posts'),
    path('search/', PostSearch.as_view()),

    # path('<int:pk>', cache_page(10*5)(PostDetailView.as_view()), name='post_detail'),
    path('<int:pk>', PostDetailView.as_view(), name='post_detail'),
    path('add/', PostCreateView.as_view(), name='post_create'),

    path('<int:pk>/edit/', PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),

    path('categories/', CategoriesListView.as_view(), name='categories'),
    path('categories/<int:pk>', CategoryDetailView.as_view(), name='category_detail'),

    path('subscribe/<int:pk>', subscribe_to, name='subscribe'),
    path('unsubscribe/<int:pk>', unsubscribe_from, name='unsubscribe'),

]

sign/urls.py
from django.urls import path, include
# from django.contrib.auth.views import LoginView, LogoutView
from .views import RegisterView, LoginView, LogoutView, upgrade_to_author

app_name = 'sign'
urlpatterns = [
   # path('login/', LoginView.as_view(template_name='sign/login.html'), name='login'),
   # path('logout/', LogoutView.as_view(template_name='sign/logout.html'), name='logout'),
   path('login/', LoginView.as_view(), name='login'),
   path('logout/', LogoutView.as_view(), name='logout'),
   path('signup/', RegisterView.as_view(), name='signup'),
   path('getauthor/', upgrade_to_author, name='getauthor'),
]

templates/layout/parts/footer.html
{#<footer class="footer mt-auto py-3 bg-light fixed-bottom">#}
{#<footer class="footer mt-auto py-3 bg-light navbar-static-bottom">#}

<!-- Footer -->
<footer class="page-footer font-small blue pt-4 bg-light">
    <div class="container-fluid text-center text-md-left">
        <div class="row">
            <div class="col-md-6 mt-md-0 mt-4">
                <p>Place sticky footer content here</p>
            </div>

            <div class="col-md-3 mb-md-0 mb-3">
                <p>---></p>
            </div>

            {% if user.is_authenticated %}
                <div class="col-md-3 mb-md-0 mb-3">
                    <button type="button" class="btn btn-outline-light me-2">
                        <a href="{% url 'sign:logout' %}" class="nav-link px-2 text">Logout</a>
                    </button>
                </div>
            {% else %}
                <div class="col-md-3 mb-md-0 mb-3">
                    <button type="button" class="btn btn-outline-light me-2">
                        <a href="{% url 'sign:login' %}" class="nav-link px-2">Login(Old)</a>
                    </button>
                    <button type="button" class="btn btn-outline-light me-2">
                        <a href="{% url 'sign:signup' %}" class="nav-link px-2 text">Sign-up(Old)</a>
                    </button>
                </div>
            {% endif %}
        </div>
    </div>
</footer>

<!-- Footer -->

templates/layout/parts/header.html
<header class="p-3 text-bg-dark fixed-top">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                    <use xlink:href="#bootstrap"/>
                </svg>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
{#                <li><a href="/news/" class="nav-link px-2 text-secondary">Новости</a></li>#}
                <li><a href="/news/" class="nav-link px-2 text-white">Новости</a></li>
                <li><a href="/news/search/" class="nav-link px-2 text-white">Поиск</a></li>
                <li><a href="/news/add/" class="nav-link px-2 text-white">Добавить</a></li>
                <li><a href="/news/categories/" class="nav-link px-2 text-white">Категории</a></li>
                <li><a href="#" class="nav-link px-2 text-white">.....</a></li>
            </ul>

            <div class="text-end">
                {% if user.is_authenticated %}
                    <button type="button" class="btn btn-outline-light me-2">
                        <a href="{% url 'sign:logout' %}" class="nav-link px-2 text">Logout</a>
                    </button>
                    <button type="button" class="btn btn-info" disabled>
{#                        <a href="{% url 'sign:logout' %}" class="nav-link px-2 text">Logout</a>#}
                    {{ user.username }}
                    </button>

                    {% if is_not_authors %}
                        <a class="btn btn-info" href="{% url 'sign:getauthor' %}">
                            Хочу стать автором!
                        </a>
                    {% else %}
                        <button type="button" class="btn btn-info" disabled>
                            Вы являетесь автором
                        </button>
                    {% endif %}

                {% else %}
                    <button type="button" class="btn btn-outline-light me-2">
                        {#                        <a href="{% url 'sign:login' %}" class="nav-link px-2">Login</a>#}
                        <a href="/accounts/login/" class="nav-link px-2">Login</a>
                    </button>
                    <button type="button" class="btn btn-outline-light me-2">
                        {#                        <a href="{% url 'sign:signup' %}" class="nav-link px-2 text">Sign-up</a>#}
                        <a href="/accounts/signup/" class="nav-link px-2">Sign-up</a>
                    </button>
                {% endif %}
            </div>
        </div>
    </div>
</header>